cd /Users/awsandy/odp/aws/sw/my-aws-samples/aws2tf-py/.python/data
rm -f import__aws_ebs_snapshot__snap-f*.tf
rm -f import__aws_ebs_snapshot__snap-e*.tf
rm -f import__aws_ebs_snapshot__snap-d*.tf
rm -f import__aws_ebs_snapshot__snap-c*.tf
rm -f import__aws_ebs_snapshot__snap-b*.tf
rm -f import__aws_ebs_snapshot__snap-a*.tf
rm -f import__aws_ebs_snapshot__snap-9*.tf
rm -f import__aws_ebs_snapshot__snap-8*.tf
rm -f import__aws_ebs_snapshot__snap-7*.tf
rm -f import__aws_ebs_snapshot__snap-6*.tf
rm -f import__aws_ebs_snapshot__snap-5*.tf
rm -f import__aws_ebs_snapshot__snap-4*.tf
rm -f import__aws_ebs_snapshot__snap-3*.tf
rm -f import__aws_ebs_snapshot__snap-2*.tf
rm -f import__aws_ebs_snapshot__snap-1*.tf
rm -f import__aws_ebs_snapshot__snap-01*.tf
rm -f import__aws_ebs_snapshot__snap-02*.tf
rm -f import__aws_ebs_snapshot__snap-03*.tf
rm -f aws_ami__ami-0f*.tf
rm -f aws_ami__ami-0e*.tf
rm -f aws_ami__ami-0d*.tf
rm -f aws_ami__ami-0c*.tf
rm -f aws_ami__ami-0b*.tf
rm -f aws_ami__ami-0a*.tf
rm -f aws_ami__ami-09*.tf
rm -f aws_ami__ami-08*.tf
rm -f aws_ami__ami-07*.tf
rm -f aws_ami__ami-06*.tf
rm -f aws_ami__ami-05*.tf
rm -f aws_ami__ami-04*.tf
rm -f aws_ami__ami-03*.tf
rm -f aws_ami__ami-02*.tf
rm -f aws_ami__ami-01*.tf
rm -f aws_ami__ami-00*.tf
rm -f aws_ami__ami-0f*.out
rm -f aws_ami__ami-0e*.out
rm -f aws_ami__ami-0d*.out
rm -f aws_ami__ami-0c*.out
rm -f aws_ami__ami-0b*.out
rm -f aws_ami__ami-0a*.out
rm -f aws_ami__ami-09*.out
rm -f aws_ami__ami-08*.out
rm -f aws_ami__ami-07*.out
rm -f aws_ami__ami-06*.out
rm -f aws_ami__ami-05*.out
rm -f aws_ami__ami-04*.out
rm -f aws_ami__ami-03*.out
rm -f aws_ami__ami-02*.out
rm -f aws_ami__ami-01*.out
rm -f aws_ami__ami-00*.out
