#!/usr/bin/env python3
"""
Create the final extended aws_dict.py by combining original with new resources
"""

import re

# Read the original aws_dict.py
with open('code/fixtf_aws_resources/aws_dict.py', 'r') as f:
    original_content = f.read()

# Read the new resources from build_extended_dict.py
with open('code/.automation/build_extended_dict.py', 'r') as f:
    new_resources_content = f.read()

# Extract individual resource definitions
pattern = r"    '(aws_[a-z_0-9]+)':\s*\{[^}]*\"clfn\":\s*\"([^\"]+)\"[^}]*\"descfn\":\s*\"([^\"]+)\"[^}]*\"topkey\":\s*\"([^\"]*)\"[^}]*\"key\":\s*\"([^\"]*)\"[^}]*\"filterid\":\s*\"([^\"]*)\"[^}]*\},"
matches = re.findall(pattern, new_resources_content, re.DOTALL)

print(f"Found {len(matches)} new resource entries")

# Format each new resource
new_entries = []
for resource_name, clfn, descfn, topkey, key, filterid in matches:
    entry = f'''
{resource_name} = {{
\t"clfn":\t\t"{clfn}",
\t"descfn":\t"{descfn}",
\t"topkey":\t"{topkey}",
\t"key":\t\t"{key}",
\t"filterid":\t"{filterid}"
}}
'''
    new_entries.append(entry)

# Create the extended dictionary file
output = []
output.append("# Extended aws_dict.py - Original + 288 new resources")
output.append("# Generated by create_extended_dict.py")
output.append("# Original resources from aws_dict.py + new resources researched from Terraform provider")
output.append("")
output.append(original_content)
output.append("")
output.append("# ============================================================================")
output.append(f"# NEW RESOURCES ADDED - {len(new_entries)} resources researched and added")
output.append("# ============================================================================")
output.append("")

for entry in new_entries:
    output.append(entry)

# Write to file
output_file = 'code/.automation/aws_dict_extended.py'
with open(output_file, 'w') as f:
    f.write('\n'.join(output))

print(f"\nCreated {output_file}")
print(f"Total new resources added: {len(new_entries)}")
print(f"\nOriginal aws_dict.py: 1317 resources")
print(f"New resources added: {len(new_entries)}")
print(f"Total in extended dict: {1317 + len(new_entries)}")
